#!/usr/bin/env ruby
# This script emulates Rails 2.x compatible Rails interface - for fun :-)

# Our filename is the command itself
ARGV.unshift File.basename(__FILE__)

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'
